<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PVSPDF</AssemblyName>
    <RootNamespace>PvsPdfApp</RootNamespace>
    <ApplicationIcon>pvspdf.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Product>ПВ-Система PDF</Product>
    <Company>ПВ-Система</Company>
    <AssemblyTitle>ПВ-Система PDF</AssemblyTitle>
    <FileVersion>1.0.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>

    <!-- Ускоряем запуск: программа отдаёт предпочтение быстрому старту
         перед оптимизацией кода, которая нужна долгим вычислениям -->
    <TieredCompilationQuickStartupJit>true</TieredCompilationQuickStartupJit>
    <TieredPGO>true</TieredPGO>
    <EventSourceSupport>false</EventSourceSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2478.35" />
  </ItemGroup>

  <ItemGroup>
    <None Include="pvspdf.ico" Condition="Exists('pvspdf.ico')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>